/* Local continuation: no group joins and no further story after recruitment. */
const AW=window.AFTER_WALL;
const awPublishOrder=['panic-teachers','panic-door','panic-home','doubt-db','doubt-drill','core','capture','dont-reply','girls1','boys1','boys2','girls2'];
function awPublication(row){const order=awPublishOrder.indexOf(row.id.replace(/^aw-/,''));return {publishOrder:order,time:'21:'+String(4+order).padStart(2,'0')}}

const awBase={openChat,chatList,home,openApp,forum,postDetail,renderMessage,sendMessage,linProfile};
let awReplyTarget=null;
const awExpanded=new Set();
function awState(){state.game.trust??={};state.game.trust.linqing??=30;const a=state.story.afterWall??={choice:null,zhouLeft:false,wallUnlocked:false,heat:10,ticks:0,recruitment:false,anomaly:false};a.departures??=a.heat>=153?1784:1327;return a}
function awReady(){return z().branch==='dormitory'&&z().phase==='finished'&&state.messages.linqing?.some(m=>m.id==='zero-warning-4')}
function awChoices(){if(!awReady()||awState().choice!==null||view!=='chat'||active!=='linqing')return;const composer=document.querySelector('#composer');if(!composer||document.querySelector('#aw-choice'))return;const input=document.querySelector('#message-input');input.disabled=true;input.placeholder='选择一条回复…';document.querySelectorAll('#composer button').forEach(b=>b.disabled=true);composer.insertAdjacentHTML('beforebegin',`<div class="zero-choices" id="aw-choice">${AW.replyChoices.map((t,i)=>`<button data-aw-choice="${i}">${esc(t)}</button>`).join('')}</div>`);scrollMessages()}
function awChoose(i){if(!awReady()||awState().choice!==null||![0,1].includes(i))return;awState().choice=i;state.game.trust.linqing=i===1?35:30;state.messages.linqing.push({id:'aw-player-reply',sender:'me',type:'text',text:AW.replyChoices[i],time:state.system.time,status:'read'});if(i===1)state.messages.linqing.push({id:'aw-trust',type:'system',text:'林晴对你的好感度发生了变化'});const c=state.contacts.find(c=>c.id==='linqing');c.preview=AW.replyChoices[i];awCommitChoice();persist();openChat('linqing');toast('校园墙突然多了很多消息')}
function awCommitChoice(){const a=awState();if(![0,1].includes(a.choice)||a.wallUnlocked)return false;a.zhouLeft=true;a.wallUnlocked=true;awInstall(AW.posts);persist();return true}
function awComment(row,id){return {id,name:row[0],author:row[0]==='肯德基蛋挞唯一真神'?'student7':'student1',text:row[1],likes:0,replies:(row[2]||[]).map((r,i)=>awComment(r,id+'-r'+i))}}
function awPost(row){return {...row,id:'aw-'+row.id,afterWall:true,title:row.title||'',category:row.recruit?'互助问答':'校园日常',...awPublication(row),replies:(row.comments||[]).map((r,i)=>awComment(r,'aw-'+row.id+'-c'+i))}}
function awInstall(rows,recruit=false){const a=awState();a.pendingPosts??=[];for(const row of [...rows].sort((x,y)=>awPublication(x).publishOrder-awPublication(y).publishOrder)){if(state.forumPosts.some(p=>p.id==='aw-'+row.id)||a.pendingPosts.some(p=>p.id===row.id))continue;a.pendingPosts.push({...row,recruit})}if(!state.forumPosts.some(p=>p.afterWall))awPublishNext()}
function awSortList(list){
 if(view!=='wall')return;
 document.querySelectorAll('.forum-page > .zero-wall-update').forEach(node=>list.append(node));
 const meta=node=>node.dataset.zeroUpdate?{date:'2045-09-07',time:Z.notices[node.dataset.zeroUpdate].time}:state.forumPosts.find(p=>p.id===(node.dataset.afterPost||node.dataset.post))||{};
 const nodes=[...list.children].filter(node=>node.matches('.forum-post,.zero-wall-update')).sort((x,y)=>{
  const a=meta(x),b=meta(y);
  const pinned=p=>p.id==='aw-core'&&awState().heat>=30?1:0;
  return pinned(b)-pinned(a)||String((b.date||'2045-09-07')+' '+(b.time||'')).localeCompare(String((a.date||'2045-09-07')+' '+(a.time||'')))||(b.publishOrder??-1)-(a.publishOrder??-1);
 });
 list.append(...nodes);
}
function awReturnFromCore(wasCore){
 const a=awState();
 if(!wasCore||view!=='wall'||!a.wallUnlocked||a.coreReturned)return;
 a.coreReturned=true;a.recruitment=true;
 awInstall(AW.recruitment,true);persist();
}
function awPublishNext(){const a=awState(),row=a.pendingPosts?.shift();if(!row)return;const p={...awPost(row),recruit:!!row.recruit};state.forumPosts.push(p);a.nextPostAt=Date.now()+3500;if(state.system.time<p.time)zeroClock(p.time);persist();if(view==='wall'&&(forumCategory==='全部'||forumCategory===p.category)){const list=document.querySelector('#forum-feed');if(list){list.insertAdjacentHTML('afterbegin',awCard(p));awSortList(list)}}}
function awExpandedRecruitmentTick(){const a=awState();if(!a.wallUnlocked||a.coreReturned||a.coreExpandedAt==null||Date.now()-a.coreExpandedAt<2000||document.hidden)return;a.coreReturned=true;a.recruitment=true;awInstall(AW.recruitment,true);const ready=(a.pendingPosts||[]).filter(p=>p.recruit);a.pendingPosts=(a.pendingPosts||[]).filter(p=>!p.recruit);for(const row of ready)if(!state.forumPosts.some(p=>p.id==='aw-'+row.id))state.forumPosts.push({...awPost(row),recruit:true});persist();if(view==='wall')forum()}
function awPublishTick(){awCommitChoice();awExpandedRecruitmentTick();if(document.hidden||!awState().wallUnlocked||!(view==='wall'||view==='post'))return;if(Date.now()>=(awState().nextPostAt||0))awPublishNext()}

function awExit(wasLin){if(!wasLin||!awCommitChoice())return;if(view==='wall')forum();else if(view==='chat'&&active==='room408')awBase.openChat('room408')}
function awNav(fn,...args){const was=view==='chat'&&active==='linqing',wasCore=view==='post'&&active==='aw-core';const result=fn(...args);awExit(was);awReturnFromCore(wasCore);return result}
openChat=function(id){awNav(awBase.openChat,id);awChoices()};
chatList=function(){return awNav(awBase.chatList)};
home=function(){return awNav(awBase.home)};
openApp=function(id){return awNav(awBase.openApp,id)};
linProfile=function(...args){return awNav(awBase.linProfile,...args)};
sendMessage=function(id,text){if(id==='linqing'&&awReady()&&awState().choice===null)return false;return awBase.sendMessage(id,text)};
renderMessage=function(m,c){let html=awBase.renderMessage(m,c);if(m.sender==='zhouhe'&&awState().zhouLeft)html=html.replace('<div class="sender-name">周禾</div>','<div class="sender-name">周禾<small class="zero-left-status">已离校</small></div>');return html};
const awMemberOptions=actions['chat-options'];
actions['chat-options']=()=>{awMemberOptions();if(active!=='room408')return;const members=state.contacts.find(c=>c.id==='room408')?.members||[];const group=document.querySelector('#overlay .section-caption')?.nextElementSibling;if(!group)return;group.innerHTML=members.map(id=>{const name={me:state.profile.name,linqing:'林晴',zhouhe:'周禾',chenyue:'陈妍'}[id]||id;const left=id==='chenyue'&&z().chenyanLeft||id==='zhouhe'&&awState().zhouLeft;return `<div class="aw-member">${id==='linqing'?`<button class="npc-avatar-button" data-action="zero-lin-profile" aria-label="查看林晴个人资料">${avatar(id)}</button>`:avatar(id)}<span>${esc(name)}</span>${left?'<small>已离校</small>':''}</div>`}).join('')};
function awLikes(p){return p.id==='aw-core'?Math.min(153,awState().heat)+(p.liked?1:0):p.likes||0}
function awCount(p){const actual=p.replies.reduce((n,c)=>n+1+c.replies.length,0);return p.id==='aw-core'?12+awState().ticks*3+p.replies.filter(c=>c.author==='me').length:actual}
function awCapture(){return `<div class="aw-capture"><small>评论截图</small><div>${forumAvatar('小咪脆角','小咪脆角','female')}<span><strong>小咪脆角</strong><small class="zero-left-status">已离校</small></span></div><p>你为什么说我消失了？</p></div>`}
function awCard(p){return `<article class="forum-post aw-post ${p.id==='aw-core'&&awState().heat>=30?'aw-core':''}" data-after-post="${p.id}"><button class="aw-post-open" data-post="${p.id}"><div class="post-author">${forumAvatar(p.author,p.name,p.gender)}<span>${esc(p.name)}<small>${esc(wallDateLabel(p))}</small></span>${p.id==='aw-core'?`<b class="aw-hot" ${awState().heat<30?'hidden':''}>热度飙升</b>`:''}</div>${p.title?`<h2 class="${p.id==='aw-core'?'aw-core-title':''}">${esc(p.title)}</h2>`:''}<p class="aw-body ${p.id==='aw-core'&&!(view==='post'&&active===p.id)?'aw-body-preview':''}">${esc(p.body)}</p>${p.capture?awCapture():''}${p.preview?`<p class="aw-group-preview">${esc(p.preview)}</p>`:''}</button><div class="post-foot"><button data-aw-like="${p.id}" aria-pressed="${!!p.liked}">${p.liked?'♥':'♡'} <span data-aw-count="${p.id}">${awLikes(p)}</span></button><button data-post="${p.id}"><span data-aw-replies="${p.id}">${awCount(p)}</span> 回复</button></div>${p.recruit?'<button class="aw-apply" data-aw-apply="true">申请加入</button>':''}</article>`}
forum=function(){const was=view==='chat'&&active==='linqing',wasCore=view==='post'&&active==='aw-core',freshExit=was&&awState().choice!==null&&!awState().zhouLeft;awBase.forum();awReturnFromCore(wasCore);awExit(was);if(freshExit)return;if(view!=='wall'||!awState().wallUnlocked)return;const list=document.querySelector('#forum-feed');if(!list)return;for(const p of state.forumPosts.filter(p=>p.afterWall)){const old=[...list.children].find(node=>node.matches('button.forum-post')&&node.dataset.post===p.id);if(old)old.outerHTML=awCard(p)}awSortList(list)};
function awCommentMarkup(c,parent=null){const departed=c.id==='aw-xiaomian';return `<div class="rule-comment ${parent?'nested-comment':''} ${departed?'aw-pinned-comment':''}" id="${c.id}">${forumAvatar(c.author,c.name,c.gender)}<div class="comment-content"><div class="comment-heading"><strong>${esc(c.author==='me'?state.profile.name:c.name)}${departed?'<small class="zero-left-status">已离校</small>':''}</strong><button data-aw-comment-like="${c.id}" aria-pressed="${!!c.liked}">${c.liked?'♥':'♡'} ${c.likes||0}</button></div>${departed?'<small class="aw-comment-pin">置顶回复</small>':''}<p>${c.replyTo?`回复 ${esc(c.replyTo)}：`:''}${esc(c.text)}</p><small class="wall-comment-time">${esc(wallDateLabel(c))}</small><button class="aw-reply-button" data-aw-reply="${c.id}" data-aw-parent="${parent||c.id}">回复</button>${!parent&&c.replies.length?`<button class="thread-toggle" data-aw-thread="${c.id}">${awExpanded.has(c.id)?'收起回复':'展开 '+c.replies.length+' 条回复'}</button>${awExpanded.has(c.id)?c.replies.map(r=>awCommentMarkup(r,c.id)).join(''):''}`:''}</div></div>`}
function awComments(p){return [...p.replies].sort((a,b)=>Number(b.id==='aw-xiaomian')-Number(a.id==='aw-xiaomian')).map(c=>awCommentMarkup(c)).join('')}
postDetail=function(id){const p=state.forumPosts.find(p=>p.id===id);if(!p?.afterWall)return awBase.postDetail(id);if(zeroLock())return;if(active!==id)awReplyTarget=null;closeSheet();stopReading();view='post';active=id;if(id==='aw-core'&&!awState().coreReturned){awState().coreExpandedAt??=Date.now();persist()}rememberRoute();screen.innerHTML=`<section class="app-page forum-page"><header class="page-head"><button class="icon-button" data-action="forum" aria-label="返回校园墙">${icon('back')}</button><h1>帖子详情</h1></header>${awCard(p)}<h3 class="reply-title">全部回复 · <span data-aw-replies="${p.id}">${awCount(p)}</span></h3><div id="aw-comments">${awComments(p)}</div><form class="rule-comment-form" id="aw-comment-form"><label>${awReplyTarget?'回复 '+esc(awReplyTarget.name):'发表评论'}</label>${awReplyTarget?'<button type="button" class="cancel-reply" data-aw-cancel="true">取消回复</button>':''}<div><input aria-label="回复内容" placeholder="说说你的想法…" maxlength="500" required><button class="pill-button" type="submit">发布</button></div></form></section>`;const input=document.querySelector('#aw-comment-form input');input.value=p.draft||'';input.oninput=()=>{p.draft=input.value;persist()};document.querySelector('#aw-comment-form').onsubmit=e=>{e.preventDefault();const text=input.value.trim();if(!text)return;if(awReplyTarget?.id==='aw-xiaomian'&&awFindComment(p,awReplyTarget.id)?.id==='aw-xiaomian'){p.draft='';awReplyTarget=null;persist();beginLateDeath('departed-reply');return;}const c={id:'aw-user-'+Date.now(),author:'me',text,date:state.system.date,time:state.system.time,likes:0,replies:[]};if(awReplyTarget){const parent=p.replies.find(r=>r.id===awReplyTarget.parent);if(!parent)return;c.replyTo=awReplyTarget.name;parent.replies.push(c);awExpanded.add(parent.id)}else p.replies.push(c);p.draft='';awReplyTarget=null;persist();postDetail(id)};screen.scrollTop=0};
function awRefreshComments(){const p=state.forumPosts.find(p=>p.id===active),el=document.querySelector('#aw-comments');if(p?.afterWall&&el)el.innerHTML=awComments(p)}
function awFindComment(p,id){for(const c of p.replies){if(c.id===id)return c;const child=c.replies.find(r=>r.id===id);if(child)return child}return null}
function awHeatTick(){const a=awState();if(!a.wallUnlocked||a.heat>=153||document.hidden)return;const core=document.querySelector('[data-after-post="aw-core"]');if(!core||!(view==='wall'||view==='post'&&active==='aw-core'))return;const r=core.getBoundingClientRect(),root=screen.getBoundingClientRect();if(view==='wall'&&(r.bottom<=root.top||r.top>=root.bottom))return;const p=state.forumPosts.find(p=>p.id==='aw-core');if(!p)return;const previous=a.heat;const increments=[12,12,24,25,8,8,12,14,14,14];a.heat=Math.min(153,a.heat+(increments[a.ticks]||10));a.ticks++;a.departures=a.heat===153?1784:Math.min(1783,a.departures+18+Math.floor(Math.random()*43));for(const [i,item] of AW.growing.entries()){if(a.heat>=item.at&&!p.replies.some(c=>c.id==='aw-growing-'+i))p.replies.push(awComment(item.comment,'aw-growing-'+i))}let inserted=false;if(a.heat>100&&!a.anomaly){a.anomaly=true;p.replies.push({id:'aw-xiaomian',name:'小咪脆角',author:'student5',text:'你为什么说我消失了？',likes:0,replies:[]});awInstall(AW.aftermath);inserted=true}persist();document.querySelectorAll('[data-aw-count="aw-core"]').forEach(el=>el.textContent=awLikes(p));document.querySelectorAll('[data-aw-replies="aw-core"]').forEach(el=>el.textContent=awCount(p));core.classList.toggle('aw-core',a.heat>=30);core.querySelector('.aw-hot').hidden=a.heat<30;const announcement=document.querySelector('[data-zero-update="departure"] p');if(announcement)announcement.textContent=zeroWallNotice('departure').text;const banner=document.querySelector('#zero-notification .opening-body>span:last-child>span');if(z().banner==='departure'&&banner)banner.textContent=zeroWallNotice('departure').text;if(view==='post')awRefreshComments();if(view==='wall'&&previous<30&&a.heat>=30){const oldTop=core.getBoundingClientRect().top;core.parentElement.prepend(core);screen.scrollTop+=core.getBoundingClientRect().top-oldTop}if(view==='wall'&&inserted){const list=core.parentElement;for(const post of state.forumPosts.filter(p=>p.afterWall)){if((forumCategory==='全部'||forumCategory===post.category)&&!list.querySelector(`[data-after-post="${post.id}"]`))list.insertAdjacentHTML('beforeend',awCard(post))}}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.awChoice!==undefined)awChoose(Number(b.dataset.awChoice));if(b.dataset.awLike){const p=state.forumPosts.find(p=>p.id===b.dataset.awLike);if(!p)return;if(p.id==='aw-core')p.likes=awLikes(p);toggleWallLike(p)}if(b.dataset.awApply){b.classList.remove('aw-pressed');void b.offsetWidth;b.classList.add('aw-pressed')}const p=state.forumPosts.find(p=>p.id===active);if(!p?.afterWall)return;if(b.dataset.awThread){const id=b.dataset.awThread;awExpanded.has(id)?awExpanded.delete(id):awExpanded.add(id);awRefreshComments()}if(b.dataset.awCommentLike){const c=awFindComment(p,b.dataset.awCommentLike);if(c){c.likes=Math.min(99,Math.max(0,(c.likes||0)+(c.liked?-1:1)));c.liked=!c.liked;persist();awRefreshComments()}}if(b.dataset.awReply){const c=awFindComment(p,b.dataset.awReply);awReplyTarget={id:c.id,parent:b.dataset.awParent,name:c.author==='me'?state.profile.name:c.name};postDetail(p.id);document.querySelector('#aw-comment-form input').focus()}if(b.dataset.awCancel){awReplyTarget=null;postDetail(p.id)}});
state.game.trust??={};state.game.trust.linqing??=30;
awState();awCommitChoice();persist();awChoices();
setInterval(awHeatTick,1000);

// Migrate recruitment published by the former heat trigger to the explicit return gate.
if(!awState().coreReturned){
 const recruitIds=new Set(AW.recruitment.map(p=>'aw-'+p.id));
 state.forumPosts=state.forumPosts.filter(p=>!recruitIds.has(p.id));
 awState().pendingPosts=(awState().pendingPosts||[]).filter(p=>!recruitIds.has('aw-'+p.id));
 awState().recruitment=false;
}
// Keep already-read posts and interactions, updating their publication metadata only.
for(const p of state.forumPosts.filter(p=>p.afterWall)){if(p.id==='aw-panic-teachers')p.body=AW.posts.find(row=>row.id==='panic-teachers').body;Object.assign(p,awPublication(p));if(p.recruit)p.category='互助问答';if(p.id==='aw-core')p.title='校园墙置顶的事情说的是真的'}
persist();
setInterval(awPublishTick,1000);
