/* Post-noodle event: persisted delivery cursor, explicit reading and reply gates. */
const EVENING_POST_ID='evening-code-warning';
const EVENING_WARNING_TITLE='⚠️大家取件一定要核对好取件码！！';
const EVENING_ROWS=[
 ['system','沈可欣已将方恬（219）移出群聊','fangtian'],['system','沈可欣已将顾遥（606）移出群聊','guyao'],
 ['jiangning','？？发生什么了'],['zhou','难道触犯了什么我们不知道的规则？'],['shen','【转发校园墙帖子】','post'],
 ['zhao','天哪，你们看校园墙显示的人数，51人'],['zhao','一次又少了六个人'],['shen','怪我大意了，没注意到第二章还有隐藏的行为规则'],['jiang','别太自责了'],['jiang','这不是你的错'],
 ['choice','所以只要干了客观意义上错误的事，就会被请离'],['me','所以只要干了客观意义上错误的事'],['me','就会被请离?'],['jiang','以后遇到需要输入的东西，先不要随便点'],['jiang','一定要确认无误再操作']];
function eveningEvent(){return state.story.eveningAnomaly}
function eveningInChat(){return view==='chat'&&active===HG_ID}
function eveningPublish(){if(state.forumPosts.some(p=>p.id===EVENING_POST_ID))return;const date=state.system.date;const reply=(name,text,time,replyTo)=>({author:name,name,text,date,time,...(replyTo?{replyTo}:{})});state.forumPosts.unshift({id:EVENING_POST_ID,name:'一只栗',author:'一只栗',gender:'female',category:'校园日常',date,time:'17:49',title:EVENING_WARNING_TITLE,body:'取件机器不知道是怎么了，不让扫码取件，硬是只能输入取件码。\n我舍友当时随便瞟了一眼就输入了，显示错误后她直接就消失了。\n太离谱了……太离谱了……',likes:0,replies:[reply('momo','我舍友按错了宿舍门锁密码，然后也不见了','17:49'),reply('开水鉴心','你们怎么是密码锁？？2045年了现在不都是刷nfc就行了吗','17:49','momo'),reply('momo','我也不知道怎么回事……就和不能扫码取件了一样莫名其妙','17:49','开水鉴心'),reply('momo','他当时想着随便试一个密码，刚确认就不见了，我后来去校园通看的密码才知道。','17:49','开水鉴心'),reply('冰美式','那就不只是取件码的问题了，任何操作都不能出错','17:49','momo')]})}
function eveningBegin(){if(eveningEvent()||!state.story.eveningNoodlesComplete)return;state.story.eveningAnomaly={phase:'transition',index:0,due:Date.now()+1500,date:state.system.date,removed:[],replyChosen:false};state.system.time='17:50';persist();eveningTransition()}
function eveningTransition(){closeSheet();view='evening-transition';active=null;rememberRoute();zeroChrome();screen.innerHTML='<section class="fa-time-transition"><h2>时间来到17:50</h2></section>'}
function eveningNotify(){if(document.querySelector('#evening-notification'))return;const el=document.createElement('div');el.id='evening-notification';el.className='opening-message';el.innerHTML='<button class="opening-body" data-evening-open>'+icon('chat')+'<span><small>讯息 · 现在</small><strong>女生B栋临时互助群</strong><span>你收到新的群消息</span></span></button>';document.querySelector('#phone').append(el)}
function eveningRemove(key){const e=eveningEvent();if(e.removed.includes(key))return;e.removed.push(key);hg().count=31-e.removed.length;const contact=hgContact();contact.status='群成员：'+hg().count+'人';const members=contact.members||[];let memberIndex=members.findIndex(id=>id===key||id===(key==='fangtian'?'record-fang':'record-gu'));if(memberIndex<0)memberIndex=members.findLastIndex(id=>id.startsWith('stranger-'));if(memberIndex>=0)members.splice(memberIndex,1);state.game.departedNpcs??={};state.game.departedNpcs[key]={date:e.date,cause:'evening-anomaly'};const clue=fa().clues.find(c=>c.id==='members');if(clue){clue.historicalRoster??=FA_ROSTER;clue.removedMembers=[...e.removed]}}
function eveningWrite(row){const e=eveningEvent(),id='evening-anomaly-'+e.index,rows=state.messages[HG_ID]??=[];if(rows.some(m=>m.id===id))return;const [who,text,kind]=row;if(who==='system')eveningRemove(kind);const p=FA_PEOPLE[who],extra=RECORD_PEOPLE[who];const time=faClockLabel(17*60+50+Math.floor(e.index/3));state.system.time=time;rows.push({id,time,gameDate:e.date,text,type:who==='system'?'system':kind==='post'?'evening-forward':'text',sender:who==='system'?undefined:who==='me'?'me':p?.avatar||'record-'+who,name:who==='me'?state.profile.name:p?p.name+'（'+p.room+'）':extra?extra[0]+'（'+extra[1]+'）':undefined,status:'read'});const c=hgContact();c.preview=kind==='post'?'[校园墙帖子] '+EVENING_WARNING_TITLE:text;c.time=time;if(!eveningInChat())c.unread=(c.unread||0)+1;persist();if(eveningInChat())openChat(HG_ID);else if(view==='messages')chatList();else status()}
function eveningDecorate(){screen.querySelector('[data-evening-choice]')?.remove();screen.querySelector('[data-evening-guide]')?.remove();const e=eveningEvent();if(!e||!eveningInChat()||['done','notice','transition'].includes(e.phase))return;const form=screen.querySelector('#composer');if(!form)return;form.querySelectorAll('button,textarea').forEach(x=>x.disabled=true);form.querySelector('textarea').placeholder='等待消息…';form.classList.toggle('story-locked',e.phase==='post');if(e.phase==='post')form.insertAdjacentHTML('beforebegin','<button class="story-guide" data-evening-guide data-evening-post>查看帖子后，返回群聊继续 <span>前往 ›</span></button>');if(e.phase==='choice')form.insertAdjacentHTML('beforebegin','<div class="zero-choices" data-evening-choice><button data-evening-reply>所以只要干了客观意义上错误的事，就会被请离</button></div>')}
function eveningTick(){if(window.mobileLaunch||['game-menu','nodes','zero-death'].includes(view)||state.game.survivalEnding)return;let e=eveningEvent();if(!e){if(state.story.eveningNoodlesComplete)eveningBegin();return}if(e.phase==='done')return;if(e.phase==='transition'){if(Date.now()<e.due)return;e.phase='notice';eveningPublish();if(!e.populationApplied){e.populationApplied=true;state.game.campusPopulation??={scope:'全校'};state.game.campusPopulation.alive=51}persist();home();eveningNotify();return}if(e.phase==='notice'){eveningNotify();return}if(e.phase==='post'){if(!e.postRead||!eveningInChat())return;e.phase='messages';e.due=Date.now()+messageSendDelay();persist();eveningDecorate();return}if(e.phase!=='messages'||Date.now()<e.due)return;const row=EVENING_ROWS[e.index];if(!row){e.phase='done';state.story.eveningAnomalyComplete=true;persist();if(eveningInChat())openChat(HG_ID);return}if(row[0]==='choice'){e.phase='choice';persist();eveningDecorate();return}eveningWrite(row);e.index++;e.due=Date.now()+messageSendDelay();if(row[2]==='post')e.phase='post';if(e.index===EVENING_ROWS.length){e.phase='done';e.completedAt=Date.now();state.story.eveningAnomalyComplete=true;persist();if(typeof startQuestionnaire==='function')startQuestionnaire();return}persist();eveningDecorate()}
messageRenderers['evening-forward']=()=>'<button class="evening-forward-card" data-evening-post><small>校园墙 · 17:49</small><strong>'+esc(EVENING_WARNING_TITLE)+'</strong><span>点击查看完整帖子</span></button>';
const eveningOpenChat=openChat;openChat=function(...args){const result=eveningOpenChat(...args);eveningDecorate();return result};
const eveningPostDetail=postDetail;postDetail=function(id){const result=eveningPostDetail(id);const e=eveningEvent();if(id===EVENING_POST_ID&&view==='post'&&e?.phase==='post'){e.postRead=true;persist();const back=screen.querySelector('.page-head button');if(back){back.removeAttribute('data-action');back.setAttribute('data-evening-back','');back.setAttribute('aria-label','返回群聊')}}return result};
const eveningSend=sendMessage;sendMessage=function(id,text){const e=eveningEvent();if(id===HG_ID&&e&&!['done','notice','transition'].includes(e.phase))return false;return eveningSend(id,text)};
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;const e=eveningEvent();if(b.hasAttribute('data-evening-open')&&e?.phase==='notice'){document.querySelector('#evening-notification')?.remove();e.phase='messages';e.due=Date.now();persist();openChat(HG_ID);eveningTick()}else if(b.hasAttribute('data-evening-post'))postDetail(EVENING_POST_ID);else if(b.hasAttribute('data-evening-back'))openChat(HG_ID);else if(b.hasAttribute('data-evening-reply')&&e?.phase==='choice'&&!e.replyChosen){e.replyChosen=true;e.index++;e.phase='messages';e.due=Date.now();persist();eveningTick();eveningDecorate()}});
function eveningClueMarkup(c){let text=esc(c.text);if(c.id!=='members')return text;text=text.replace(/目前\d+名成员/,'目前<span data-group-roster-count>'+hg().count+'</span>名成员');const removed=new Set([...(c.removedMembers||[]),...Object.keys(state.game.departedNpcs||{})]);const roster=esc(faText(c.historicalRoster||FA_ROSTER)).replace(/当前成员：\d+人/,'当前成员：<span data-group-roster-count>'+hg().count+'</span>人').replace(/([^\s、：]+)(\d{3})(?=、|\n|$)/g,(label,name)=>{const key=Object.keys(GROUP_SUSPECT_NAMES).find(key=>GROUP_SUSPECT_NAMES[key]===name);return key&&removed.has(key)?'<del class="evening-former-member">'+label+'</del>（已离校）':label});return text+'\n\n'+roster}
const eveningNoodleFinish=noodleFinish;noodleFinish=function(){eveningNoodleFinish();eveningBegin()};
function migrateEveningPopulation(){let changed=false;for(const rows of Object.values(state.messages||{}))for(const m of rows||[])if(m.text){const next=m.text.replaceAll('天哪，你们看校园墙显示的人数，123人','天哪，你们看校园墙显示的人数，51人').replaceAll('当前存活人数：123人','当前存活人数：51人');if(next!==m.text){m.text=next;changed=true}}const population=state.game.campusPopulation;if(state.story.eveningAnomaly&&population?.alive===123){population.alive=51;changed=true}if(changed)persist()}
migrateEveningPopulation();
setInterval(eveningTick,200);if(eveningEvent()?.phase==='transition')eveningTransition();else if(eveningEvent()?.phase==='notice'&&!window.mobileLaunch)eveningNotify();else eveningDecorate();
