/* Food conversation after the public-role discussion. Scene assets are replaceable. */
const FOOD_CG={node:'day1-linqing-food',images:{intro:'assets/food-cg-dorm.jpg?v=20261011-rc4',gift:'assets/food-cg-dorm.jpg?v=20261011-rc4'},choices:['有所隐瞒','如实回答']};
function foodCG(){return state.story.foodCG??={phase:'intro',index:0,choice:null,giftReceived:false,due:0}}
function foodRender(fade=true){const previous=captureSceneSnapshot(screen);rd().phase='cg';const a=foodCG();view='role-discussion-cg';active=null;closeSheet();rememberRoute();const image=FOOD_CG.images[['gift','bag-teaching'].includes(a.phase)?'gift':'intro'];screen.innerHTML=`<section class="rd-cg food-cg">${image?`<img src="${esc(image)}" alt="宿舍场景">`:'<div class="rd-cg-placeholder" aria-label="可替换的宿舍场景画面"></div>'}</section>`;zeroChrome();const host=screen.firstElementChild;
 if(a.phase==='bag-teaching'){foodBagTeaching();return}if(a.phase==='intro'&&a.index>=2){a.phase='choice';a.index=0}if(a.phase==='choice-wait')a.phase='choice';if(['choice-wait','choice'].includes(a.phase)){host.insertAdjacentHTML('beforeend',`<div class="vn-dialogue"><div class="vn-speaker">${avatar('linqing')}<div class="vn-copy"><strong class="vn-name">林晴</strong><p class="vn-text">你有吃的吗？</p></div></div></div>${a.phase==='choice'?`<div class="food-cg-options cg-options">${FOOD_CG.choices.map((t,i)=>`<button data-action="zero-food-${i}">${esc(cgText(t,'me'))}</button>`).join('')}</div>`:''}`);if(a.phase==='choice')recordStoryChoice(FOOD_CG.node)}else{const rows=a.phase==='intro'?[{speaker:'linqing',text:state.profile.name},{speaker:'me',text:'怎么了？'},{speaker:'linqing',text:'你有吃的吗？'}]:a.phase==='answer'?[{speaker:'me',text:a.choice===0?'没有了':'还有一桶泡面，但没水可以泡了'}]:['床另一头的林晴伸出了一只手，给你递来了一根士力架。','你接过士力架，把它收进了背包。\n获得：士力架×1',{speaker:'me',text:'天哪，谢谢你。'},{speaker:'linqing',text:'没事，我有很多。'}];CGDialogue.present(host,rows,{index:a.index,firstReplyConfirmed:a.phase==='answer'&&[0,1].includes(a.choice),onIndex:i=>{a.index=i;if(a.phase==='gift'&&i===1)foodReceive();if(a.phase==='gift'&&i===2&&!a.bagTeachingSeen){a.phase='bag-teaching';persist();foodRender(false);return}if(a.phase==='intro'&&i===2){a.phase='choice';a.index=0;persist();foodRender(false);return}persist()},onComplete:()=>{if(a.phase==='intro'){a.phase='choice';a.due=0;a.index=0;persist();foodRender(false)}else if(a.phase==='answer'){a.phase='gift';a.index=0;persist();foodRender(true)}else foodFinish()}})}persist();cgScreenCrossfade(previous)}
function foodChoose(choice){const a=foodCG();if(a.phase!=='choice'||![0,1].includes(choice)||a.choice!==null)return;recordStoryChoice(FOOD_CG.node);a.choice=choice;state.game.trust??={};state.game.trust.linqing=(state.game.trust.linqing??30)+(choice===0?-5:5);a.phase='answer';a.index=0;persist();foodRender(false)}
function foodReceive(){const a=foodCG();if(a.giftReceived)return;state.game.inventory??=[];const item=state.game.inventory.find(p=>p.id==='linqing-snickers');if(item)item.quantity++;else state.game.inventory.push({id:'linqing-snickers',name:'士力架',category:'能量棒',quantity:1});a.giftReceived=true;persist()}
function foodBagTeaching(){foodReceive();sheet('物品已放入背包','<p>点击“健康状态”App即可查看背包并使用物品。</p><button class="primary" data-action="zero-food-bag">知道了</button>');document.querySelector('#overlay .sheet-header button')?.remove()}
actions['zero-food-bag']=()=>{const a=foodCG();if(a.phase!=='bag-teaching')return;a.bagTeachingSeen=true;a.phase='gift';a.index=2;persist();closeSheet();foodRender(false)};
function foodFinish(){const a=foodCG();if(a.phase==='done')return;foodReceive();a.phase='done';rd().phase='done';persist();home()}
rdScene=function(fade=true){foodRender(fade)};
STORY_CHOICES.push({id:FOOD_CG.node,title:'回应林晴的食物询问',day:'第一日 · 中午',chat:'room408'});
Object.assign(actions,{'zero-food-0':()=>foodChoose(0),'zero-food-1':()=>foodChoose(1)});
const foodStyle=document.createElement('style');foodStyle.textContent='.food-cg-options{position:absolute;left:22px;right:22px;bottom:235px;display:grid;gap:10px}.food-cg-options button{padding:15px;border-radius:16px;background:#d1bacddf;color:#392d3c;border:1px solid #e4d2e24d;backdrop-filter:blur(10px)}';document.head.append(foodStyle);
setInterval(()=>{if(view==='role-discussion-cg'&&rd().phase==='cg'&&foodCG().phase==='choice-wait'&&Date.now()>=foodCG().due){foodCG().phase='choice';persist();foodRender(false)}},250);
if(rd().phase==='cg'&&!['game-menu','nodes'].includes(view))foodRender(false);
