/* Four investigations per day; shared schedule for prompts and settlement. */
const FREE_ACTION_LIMIT=4;
const FREE_ACTION_TIMES=['13:00','14:00','15:00','16:00'];
const FREE_REST_ACTION={id:'d2sleep',name:'睡一觉',description:'休息一下，精力值+20',icon:'moon'};
const FREE_ACTIONS=[
 {id:'cheng',name:'在群内和程昕对峙',description:'查看群内的讨论',icon:'chat'},
 {id:'door',name:'查看408智能门锁',description:'查看宿舍门锁信息',icon:'lock'},
 {id:'author',name:'调查黑头像发布者',description:'查看校园墙发布者',black:true},
 {id:'wen',name:'私聊温宁',description:'查看温宁的讯息',avatar:'npc-wenning'},
 {id:'zhao',name:'私聊赵诗雨',description:'查看赵诗雨的讯息',avatar:'npc-zhaoshiyu'},
 {id:'members',name:'整理群成员楼层',description:'查看互助群成员',icon:'user'},
 {id:'lin',name:'私聊林晴',description:'查看林晴的讯息',avatar:'linqing'}
];
function freeState(){const f=state.story.freeAction??={unlocked:false,promptSeen:false,completed:[],newCards:[],seenUnlocks:[],chengConfirmed:false};if(f.scheduleVersion!==4){f.scheduleVersion=4;const count=f.completed.length;const alreadyAfter=!!state.story.afternoonPickup;if(!alreadyAfter&&count<FREE_ACTION_LIMIT){f.finished=false;if(f.transition)f.transition.time=FREE_ACTION_TIMES[count-1];if(f.unlocked&&count>0&&!f.run)state.system.time=FREE_ACTION_TIMES[count-1]}}return f}
function freeAvailable(id){const f=freeState();return id==='cheng'?f.chengConfirmed:id==='zhao'?f.completed.includes('wen'):id==='lin'?f.completed.includes('door'):true}
function freeSync(){const f=freeState();for(const id of ['cheng','zhao','lin'])if(freeAvailable(id)&&!f.seenUnlocks.includes(id)){f.seenUnlocks.push(id);f.newCards.push(id)}const app=C.apps.find(a=>a.id==='free-action');app.visible=f.unlocked;app.locked=(f.finished||f.completed.length>=FREE_ACTION_LIMIT);}
C.apps.push({id:'free-action',name:'自由行动',icon:'search',tone:'sand',visible:false});C.homeLayout.main.push('free-action');
function freeCard(a){const f=freeState(),done=a.id!=='d2sleep'&&f.completed.includes(a.id),available=freeAvailable(a.id),fresh=f.newCards.includes(a.id);return `<button class="free-card ${done?'done':available?'available':'unavailable'} ${fresh?'fresh':''}" data-free-card="${a.id}" ${done?'disabled':''}>${available?`${fresh?'<small class="free-new">NEW</small>':''}<span class="free-card-art">${a.avatar?avatar(a.avatar):a.black?'<i class="free-black-avatar"></i>':icon(a.icon)}</span><strong>${a.name}</strong><p>${a.description}</p>`:'<span class="free-unknown" aria-label="未解锁">'+ '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M16 17a8 8 0 1 1 13 6c-4 2-5 4-5 7"/><circle cx="24" cy="37" r="1" fill="currentColor"/></svg><span class="free-unknown-label">？？？</span></span>'}<span class="free-card-state">${done?icon('check')+'已完成':available?'可调查':a.id==='cheng'?'缺少前置线索：不妨去校园墙找找':'缺少前置条件'}</span></button>`}
function freePanel(){const f=freeState();if(!f.unlocked)return;if((f.finished||f.completed.length>=FREE_ACTION_LIMIT))return toast('今日自由行动已结束');if(f.run&&typeof faReturnToAction==='function')return faReturnToAction();closeSheet();delete f.recoveryHealthReturn;view='free-action';active=null;freeSync();rememberRoute();screen.innerHTML=`<section class="app-page free-page">${head('自由行动')}<div class="free-kicker">午后 · 留给自己的时间</div><article class="free-status"><span>当前时间</span><strong>${esc(state.system.time)}</strong><p>16:00前不得离开宿舍</p><div class="free-remaining"><span>剩余行动 <b>${FREE_ACTION_LIMIT-f.completed.length}次</b></span><div class="free-dots" aria-label="剩余${FREE_ACTION_LIMIT-f.completed.length}次行动">${Array.from({length:FREE_ACTION_LIMIT},(_,i)=>i).map(i=>`<i class="${i<f.completed.length?'used':''}"></i>`).join('')}</div></div></article><p class="free-caption">调查结果可能影响今晚的检举。</p><div class="free-grid">${((state.game.spirit??100)<20||f.recoveryPromptSeen?[...FREE_ACTIONS,FREE_REST_ACTION]:FREE_ACTIONS).map(freeCard).join('')}</div></section>`;f.newCards=[];persist();freeRecoveryPrompt()}
function freeConfirm(id){const f=freeState(),a=id==='d2sleep'?FREE_REST_ACTION:FREE_ACTIONS.find(a=>a.id===id);if(!f.unlocked||!a||(id!=='d2sleep'&&f.completed.includes(id))||(f.finished||f.completed.length>=FREE_ACTION_LIMIT))return;if(f.run)return faReturnToAction();if(!freeAvailable(id))return toast(id==='cheng'?'缺少前置线索：不妨去校园墙找找':'缺少前置条件');sheet(a.name,`<p>本次调查将消耗一次行动机会。</p><p>完成后时间将推进至${FREE_ACTION_TIMES[f.completed.length]}。</p><button class="primary" data-fa-start="${id}">开始调查</button><button class="secondary" data-action="close">再想想</button>`)}
function freePrompt(){if(freeRecoveryPrompt())return;const f=freeState();if(!f.unlocked||f.promptSeen||f.run||(f.finished||f.completed.length>=FREE_ACTION_LIMIT))return;sheet('自由行动已开放','<p>16:00前，你可以进行四次调查。</p><button class="primary" data-action="free-start">开始调查</button>');}
const freeHome=home;home=function(...args){freeSync();if(freeState().transition&&typeof faTransition==='function')return faTransition();return freeHome(...args)};
const freeOpenApp=openApp;openApp=function(id){if(id==='free-action'){if(zeroLock())return;return freePanel()}return freeOpenApp(id)};
const freeFoodFinish=foodFinish;foodFinish=function(){const wasDone=foodCG().phase==='done';const previous=captureSceneSnapshot(screen);freeFoodFinish();if(wasDone)return;const f=freeState();f.unlocked=true;zeroClock('12:00');freeSync();home();zeroDissolve(previous);persist();storyTimeout(()=>{if(view==='home'&&freeState().unlocked)freePrompt()},1800)};
function confirmIdentifierClue(key){if(key==='cheng'&&identifierQuery.trim().toLowerCase()==='celine07'){freeState().chengConfirmed=true;freeSync();persist()}}
const freeSearchProfile=identifierSearchProfile;identifierSearchProfile=function(key){freeSearchProfile(key);if(view==='contact-public-profile')confirmIdentifierClue(key)};
actions['free-start']=()=>{freeState().promptSeen=true;persist();freePanel()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-free-card]');if(b)freeConfirm(b.dataset.freeCard)});
if(state.story.foodCG?.phase==='done'&&!state.story.freeAction?.unlocked){freeState().unlocked=true;zeroClock('12:00');persist()}
freeSync();if(view==='home'){home();if(freeState().unlocked&&!freeState().promptSeen)freePrompt()}else if(view==='free-action')freePanel();
