/* Jiang Xiao's warning, only after the safe supply-event convergence. */
const JX=window.JIANGXIAO_STORY;
function jx(){return state.story.jiangxiao??={phase:'idle',accepted:false,due:0,step:0,choice:null,waiting:false,banner:null}}
function jxContact(){return state.contacts.find(c=>c.id===JX.id)}
function jxNotice(kind){jx().banner=kind;document.querySelector('#jx-notification')?.remove();persist();if(!kind)return;const el=document.createElement('div');el.id='jx-notification';el.className='opening-message';el.innerHTML=`<button class="opening-body" data-action="jx-notice"><span>${avatar(JX.avatar)}</span><span><small>讯息 · 现在</small><strong>${kind==='friend'?'江晓（316） · 好友申请':'江晓'}</strong><span>${kind==='friend'?'来自“女生B栋临时互助群” · 有件事只能单独和你说':esc(jxContact()?.preview||'你收到一条消息')}</span></span></button>${kind==='friend'?'':'<button class="opening-close" data-action="jx-dismiss" aria-label="关闭消息通知">×</button>'}`;document.querySelector('#phone').append(el)}
function jxFriend(){if(jx().phase!=='friend')return;closeSheet();jxNotice(null);view='jx-friend';active=null;rememberRoute();screen.innerHTML=`<section class="app-page">${head('好友申请')}<div class="panel"><div class="profile-row">${avatar(JX.avatar)}<div><h2>江晓（316）</h2><p>来自“女生B栋临时互助群”</p></div></div><p>验证消息：有件事只能单独和你说</p><button class="primary" data-action="jx-accept">同意</button></div></section>`}
function jxAccept(){if(jx().phase!=='friend'||jx().accepted)return;jx().accepted=true;state.game.trust??={};state.game.trust.jiangxiao=10;state.game.npcSecrets??={};state.game.npcSecrets.jiangxiao=structuredClone(JX.hidden);state.contacts.push({id:JX.id,name:'江晓',avatar:JX.avatar,online:true,status:'在线',time:'09:18',preview:'你们已成为联系人',unread:0});state.messages[JX.id]=[{id:'jx-friend-added',type:'system',text:'你们已成为联系人',time:'09:18'}];jx().phase='greeting';jx().due=Date.now()+messageSendDelay();persist();screen.innerHTML=`<section class="app-page">${head('好友申请')}<div class="panel"><div class="profile-row">${jxAvatarButton()}<h2>江晓（316）</h2></div><p class="subtle">已添加为联系人</p></div></section>`}
function jxAvatarButton(){return `<button class="npc-avatar-button" data-action="jx-profile" aria-label="查看江晓个人资料">${avatar(JX.avatar)}</button>`}
function jxAdd(text,id,player=false,time='09:19'){const rows=state.messages[JX.id];if(rows.some(m=>m.id===id))return;rows.push({id,type:'text',sender:player?'me':JX.avatar,text,time,...(player?{status:'read'}:{})});const contact=jxContact();contact.preview=(player?'我：':'')+text;contact.time=time;const inside=view==='chat'&&active===JX.id;if(!inside&&!player){contact.unread++;jx().waiting=!jx().readStarted}persist();if(inside)openChat(JX.id);else{status();if(view==='messages')chatList();if(!player&&!jx().readStarted)jxNotice('message')}}
function jxChoose(index){if(view!=='chat'||active!==JX.id||![0,1].includes(index))return;const a=jx();if(a.phase==='intro-choice'){a.phase='warning';a.due=Date.now()+messageSendDelay();jxAdd(JX.introChoices[index],'jx-intro-answer',true)}else if(a.phase==='warning-choice'&&a.choice===null){recordStoryChoice(JX.node);a.choice=index;state.game.trust.jiangxiao+=(index===0?-5:10);a.phase='reply';a.step=0;a.due=Date.now()+messageSendDelay();jxAdd(JX.choices[index],'jx-warning-answer',true)}persist()}
const jxBase={openChat,renderMessage,sendMessage,chatList,initializeChapter,retryStoryChoice};
openChat=function(id){jxBase.openChat(id);if(id!==JX.id||view!=='chat'||active!==id)return;jx().readStarted=true;persist();if(jx().banner==='message')jxNotice(null);if(jx().waiting){jx().waiting=false;jx().due=Date.now()+(['intro-ready','warning-ready'].includes(jx().phase)?STORY_CHOICE_DELAY:messageSendDelay());persist()}const face=screen.querySelector('.chat-head>.avatar');if(face)face.outerHTML=jxAvatarButton();const composer=screen.querySelector('#composer');if(!composer)return;const input=composer.querySelector('textarea');input.disabled=true;input.placeholder=jx().phase==='done'?'暂无新消息':'等待江晓的消息…';composer.querySelectorAll('button').forEach(b=>b.disabled=true);const options=jx().phase==='intro-choice'?JX.introChoices:jx().phase==='warning-choice'?JX.choices:null;if(options){input.placeholder='选择一条回复…';if(jx().phase==='warning-choice')recordStoryChoice(JX.node);composer.insertAdjacentHTML('beforebegin',`<div class="zero-choices">${options.map((text,i)=>`<button data-jx-choice="${i}">${esc(text)}</button>`).join('')}</div>`)}scrollMessages()};
renderMessage=function(m,c){const html=jxBase.renderMessage(m,c);return (c.id===JX.id&&m.sender===JX.avatar||c.id===HG_ID&&m.hgWho==='jiang'&&jx().accepted)?html.replace(avatar(JX.avatar),jxAvatarButton()):html};
sendMessage=function(id,text){if(id===JX.id)return false;return jxBase.sendMessage(id,text)};
chatList=function(){jxBase.chatList();if(view==='messages'&&jx().phase==='friend')screen.querySelector('.page-head')?.insertAdjacentHTML('afterend','<button class="setting-row" data-action="jx-friend">新的好友申请<span>江晓 ›</span></button>')};
let jxOrigin={chat:JX.id,members:false};
function jxProfile(returning=false){if(!jx().accepted||zeroLock())return;if(!returning)jxOrigin={chat:active||JX.id,members:!!document.querySelector('#overlay .sheet')};closeSheet();view='jx-profile';active=null;screen.innerHTML=`<section class="app-page lin-profile"><header class="page-head"><button class="icon-button" data-action="jx-back" aria-label="返回聊天">${icon('back')}</button><h1>个人资料</h1></header><div class="lin-profile-card">${avatar(JX.avatar)}<h2>江晓</h2><p>女生B栋 · 316</p></div><div class="settings-group">${settingItem('photo','朋友圈','jx-moments')}</div></section>`;screen.scrollTop=0}
function jxMoments(){if(!jx().accepted||zeroLock())return;closeSheet();view='jx-moments';active=null;const m=JX.moment;screen.innerHTML=`<section class="app-page lin-moments"><header class="page-head"><button class="icon-button" data-action="jx-profile-return" aria-label="返回江晓个人资料">${icon('back')}</button><h1>江晓的朋友圈</h1></header><div class="lin-feed-owner">${avatar(JX.avatar)}<div><strong>江晓</strong></div></div><article class="lin-moment"><time>${esc(m.date)}</time><p class="lin-moment-text">${esc(m.text)}</p>${m.image?`<div class="lin-moment-photo"><img src="${esc(m.image)}" alt="${esc(m.imageAlt)}"></div>`:''}<div class="lin-existing-replies">${m.replies.map(r=>`<p><strong>${esc(r.name)}</strong>${r.replyTo?`<span>回复</span><strong>${esc(r.replyTo)}</strong>`:''}：${esc(r.text)}</p>`).join('')}</div></article></section>`;screen.scrollTop=0}
const jxMembersBase=actions['chat-options'];actions['chat-options']=()=>{jxMembersBase();if(active!==HG_ID||!jx().accepted)return;document.querySelectorAll('#overlay .setting-row').forEach(row=>{if(row.textContent.includes('江晓（316）')){const a=row.querySelector('.avatar');if(a&&!a.closest('button'))a.outerHTML=jxAvatarButton()}})};
Object.assign(actions,{'jx-notice':()=>jx().banner==='friend'?jxFriend():openChat(JX.id),'jx-friend':jxFriend,'jx-accept':jxAccept,'jx-dismiss':()=>jxNotice(null),'jx-profile':()=>jxProfile(),'jx-profile-return':()=>jxProfile(true),'jx-moments':jxMoments,'jx-back':()=>{openChat(jxOrigin.chat);if(jxOrigin.members)actions['chat-options']()}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-jx-choice]');if(b)jxChoose(Number(b.dataset.jxChoice))});
function jxTick(){if(!state.story.started||document.hidden||zeroLock()||['game-menu','nodes'].includes(view))return;const a=jx(),now=Date.now();if(a.phase==='idle'){if(fm().phase!=='common'||!state.story.morningCommonReady||document.querySelector('.opening-message,#overlay .sheet,.zero-transition'))return;a.phase='friend';zeroClock('09:18');jxNotice('friend');return}if(a.waiting||now<a.due)return;if(a.phase==='greeting'){zeroClock('09:19');a.phase='intro-ready';a.due=now+STORY_CHOICE_DELAY;jxAdd(JX.greeting,'jx-greeting')}else if(a.phase==='intro-ready'||a.phase==='warning-ready'){if(view!=='chat'||active!==JX.id)return;a.phase=a.phase==='intro-ready'?'intro-choice':'warning-choice';openChat(JX.id)}else if(a.phase==='warning'){a.phase='warning-ready';a.due=now+STORY_CHOICE_DELAY;jxAdd(JX.warning,'jx-warning')}else if(a.phase==='reply'){const rows=[...JX.replies[a.choice],...JX.closing];if(a.step<rows.length){const i=a.step++;a.due=now+messageSendDelay();if(i===rows.length-1)a.finishedAt=now;const merged=i>=JX.replies[a.choice].length;if(merged)zeroClock('09:20');jxAdd(rows[i],'jx-reply-'+i,false,merged?'09:20':'09:19')}else{a.phase='done';if(view==='chat'&&active===JX.id)openChat(JX.id)}}else return;persist()}
STORY_CHOICES.push({id:JX.node,title:'回应江晓的提醒',day:'第一日 · 上午',chat:JX.id});

initializeChapter=function(...args){document.querySelector('#jx-notification')?.remove();return jxBase.initializeChapter(...args)};
if(jx().banner)jxNotice(jx().banner);
setInterval(jxTick,250);

// Only migrate the old saved-contact label; a saved offline friend is not a new friend.
function syncSavedFriendOnline(progress){
 let changed=false;
 for(const c of progress?.contacts||[]){
  if(!['shen-friend',JX.id].includes(c.id))continue;
  const key=c.id===JX.id?'jiang':'shen',gone=progress.game?.departedNpcs;
  const departed=gone?.[key]||gone?.[c.id]||gone?.[c.name]||/已离校|已注销|已请离|被请离|已清理/.test(c.status||'');
  if(departed){if(c.online!==false){c.online=false;changed=true}if(!/已离校|已注销|已请离|被请离|已清理/.test(c.status||'')){c.status='已离校';changed=true}}
  else if(c.status==='已保存联系人'){c.status='在线';c.online=true;changed=true}
 }
 return changed;
}
if(syncSavedFriendOnline(state))persist();
storySnapshotMigrations.push(syncSavedFriendOnline);

// Update closing messages already present in the current progress.
{const rows=state.messages[JX.id]||[];let changed=false;for(const m of rows){if(m.id?.startsWith('jx-reply-')&&JX.closing.includes(m.text)&&m.time!=='09:20'){m.time='09:20';changed=true}}if(changed){const c=jxContact();if(c&&JX.closing.includes(rows.at(-1)?.text))c.time='09:20';if(state.system.time==='09:19'&&jx().phase==='done')state.system.time='09:20';persist()}}
