/* Bottom navigation and a chronological friends-only feed. */
const socialList=chatList;
const messageSafeAreaStyle=document.createElement('style');messageSafeAreaStyle.textContent='.messages-shell .app-page,.chat-page,.lin-moments{position:relative;box-sizing:border-box;padding-top:86px}.messages-shell .app-page:before,.chat-page:before,.lin-moments:before{content:"CAMPUS MESSAGE  ·  校内加密通讯";position:absolute;top:30px;left:19px;right:19px;height:24px;display:flex;align-items:center;border-bottom:1px solid #ffffff0a;color:#71818a;font:9px/1.2 monospace;letter-spacing:1.5px;pointer-events:none}.chat-page:before{left:14px;right:14px}.messages-shell .moments-feed,.messages-shell .moments-directory{padding-top:86px}@media(max-height:650px){.messages-shell .app-page,.chat-page,.lin-moments,.messages-shell .moments-feed,.messages-shell .moments-directory{padding-top:76px}.messages-shell .app-page:before,.chat-page:before,.lin-moments:before{top:24px}}';document.head.append(messageSafeAreaStyle);
function messageTabs(selected){return `<nav class="message-tabs">${[['messages','chat','讯息','message-conversations'],['contacts','user','通讯录','message-contacts'],['moments','photo','朋友圈','message-moments']].map(([id,image,label,action])=>`<button data-action="${action}" class="${selected===id?'selected':''}" aria-current="${selected===id?'page':'false'}">${icon(image)}<span>${label}</span></button>`).join('')}</nav>`}
const messageBottom=document.createElement('div');messageBottom.id='message-bottom';document.querySelector('#phone').insertBefore(messageBottom,document.querySelector('#dock'));
function syncMessageTabs(){const selected={messages:'messages','message-contacts':'contacts','message-moments':'moments','moment-compose':'moments'}[view];document.querySelector('#phone').classList.toggle('messages-shell',!!selected);messageBottom.hidden=!selected;if(selected&&messageBottom.dataset.selected!==selected){messageBottom.dataset.selected=selected;messageBottom.innerHTML=messageTabs(selected)}}
chatList=function(...args){const result=socialList(...args);screen.querySelector('.message-tabs')?.remove();if(view==='messages'){closeSheet();screen.scrollTop=0}syncMessageTabs();return result};
function messageContacts(){if(zeroLock())return;closeSheet();view='message-contacts';active=null;rememberRoute();const friends=state.contacts.filter(c=>!c.members&&!c.systemAccount);screen.innerHTML=`<section class="app-page"><header class="page-head">${avatar('me')}<h1>通讯录</h1></header><div class="list-label"><span>我的好友</span><span>${friends.length} 位</span></div>${friends.map(c=>{const person=messageIdentifiers().find(p=>p.contact===c.id);return `<div class="address-friend"><button data-contact="${esc(c.id)}">${avatar(c.avatar)}<span><strong>${esc(c.name)}</strong>${person?`<small>${esc(person.handle)}</small>`:''}</span></button>${person?`<button class="address-detail" data-identifier-profile="${person.key}" aria-label="查看${esc(c.name)}资料">${icon('user')}</button>`:''}</div>`}).join('')}<section class="address-search"><div class="contact-search-intro"><small>找到你的朋友</small><h2>通过讯息号查找</h2></div><form id="contacts-handle-search"><label class="search">${icon('search')}<input aria-label="搜索讯息号" placeholder="输入讯息号，查找朋友" autocomplete="off" autocapitalize="none" spellcheck="false" value="${esc(identifierQuery)}"></label><button type="submit" class="contact-search-submit">查找</button></form><div id="identifier-result" aria-live="polite"></div></section></section>`;screen.querySelector('#contacts-handle-search').onsubmit=e=>{e.preventDefault();identifierQuery=e.currentTarget.querySelector('input').value.trim();identifierSearched=true;const person=renderInlineIdentifierResult();if(person&&typeof confirmIdentifierClue==='function')confirmIdentifierClue(person.key)};renderInlineIdentifierResult();screen.scrollTop=0;syncMessageTabs()}

function momentTimestamp(date){const n=date.match(/\d+/g)?.map(Number)||[];return Date.UTC(n[0]||0,(n[1]||1)-1,n[2]||1,n[3]||0,n[4]||0)}
function friendsMomentRows(){return [{key:'lin',name:'林晴',avatar:'linqing',contact:'linqing',posts:(state.contactProfiles?.linqing||Z.linqingProfile).moments},{key:'shen',name:'沈可欣',avatar:'shen',contact:'shen-friend',posts:SHEN_PROFILE.moments},{key:'jiang',name:'江晓',avatar:JX.avatar,contact:JX.id,posts:[JX.moment]},...Object.entries(state.contactProfiles||{}).filter(([id])=>id!=='linqing').map(([id,p])=>({key:id,name:p.name,avatar:p.avatar,contact:id,posts:p.moments}))].filter(p=>state.contacts.some(c=>c.id===p.contact&&!c.members)).flatMap(p=>p.posts.filter(m=>!m.condition||state.game.flags?.[m.condition]).map((m,i)=>({...p,post:m,rowKey:p.key+'-'+i}))).sort((a,b)=>momentTimestamp(b.post.date)-momentTimestamp(a.post.date))}
messageMoments=function(){if(zeroLock())return;closeSheet();view='message-moments';active=null;rememberRoute();screen.innerHTML=`<section class="app-page moments-feed"><header class="page-head"><h1>朋友圈</h1><button class="icon-button" data-action="moment-compose" aria-label="发朋友圈">${icon('camera')}</button></header><div class="feed-heading"><span>朋友的生活碎片</span>${avatar('me')}</div>${friendsMomentRows().map(p=>{const m=p.post;return `<article class="friends-moment"><button class="friend-post-avatar" data-action="message-moments-${p.key}" aria-label="查看${p.name}的朋友圈">${avatar(p.avatar)}</button><div class="friend-post-content"><button class="friend-post-name" data-action="message-moments-${p.key}">${p.name}</button>${m.text?`<p class="lin-moment-text">${esc(momentText(m.text))}</p>`:''}${m.image?`<div class="lin-moment-photo"><img src="${esc(m.image)}" alt="${esc(m.imageAlt||'朋友圈配图')}" loading="lazy"></div>`:''}${momentLinkCard(m)}${m.music?`<button class="lin-music-card" data-action="zero-lin-music" aria-label="播放音乐" aria-pressed="false"><span class="lin-music-art"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 17V5l11-2v12M9 9l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/></svg></span><span class="lin-music-info"><strong>${esc(m.music.title)}</strong><small>${esc(m.music.artist)}</small></span><span class="lin-music-open">▷</span></button>`:''}<time>${esc(m.date)}</time>${m.replies?.length?`<div class="lin-existing-replies">${m.replies.map(r=>`<p><strong>${esc(momentText(r.name))}</strong>${r.replyTo?`<span>回复</span><strong>${esc(momentText(r.replyTo))}</strong>`:''}：${esc(momentText(r.text))}</p>`).join('')}</div>`:''}</div></article>`}).join('')}</section>`;screen.scrollTop=0;syncMessageTabs()};
function messageContactDeparted(contact){
 if(!contact||contact.members||contact.systemAccount)return false;
 if(/已离校|已注销|已请离|被请离|已清理/.test(contact.status||''))return true;
 const name=String(contact.name||'').replace(/[（(].*$/,'').trim(),matches=(id,label)=>contact.id===id||contact.avatar===id||name===label;
 const story=state.story;
 if(story.zero?.chenyanLeft&&matches('chenyue','陈妍')||story.afterWall?.zhouLeft&&matches('zhouhe','周禾')||story.firstMorning?.suDeparted&&matches('su','苏沐')||story.helpGroup?.xuLeft&&matches('xu','许知夏'))return true;
 const keys=new Set([...(story.firstMorning?.left||[]),...(story.eveningAnomaly?.removed||[]),...Object.keys(state.game.departedNpcs||{})]);
 for(const key of keys){
  const person=typeof FA_PEOPLE!=='undefined'?FA_PEOPLE[key]:null,member=typeof HG_PEOPLE!=='undefined'?HG_PEOPLE[key]:null,label=typeof GROUP_SUSPECT_NAMES!=='undefined'?GROUP_SUSPECT_NAMES[key]:null;
  if(matches(key,label)||person&&(contact.id===person.contact||contact.avatar===person.avatar||name===person.name)||member&&(contact.avatar===member.avatar||name===member.name.replace(/[（(].*$/,'')))return true;
 }
 return false;
}
const messageContactsBase=messageContacts;messageContacts=function(){messageContactsBase();for(const button of screen.querySelectorAll('.address-friend>[data-contact]')){const contact=state.contacts.find(c=>c.id===button.dataset.contact),name=button.querySelector('strong');if(name&&messageContactDeparted(contact)){name.classList.add('contact-departed');name.title='已离校'}}};actions['message-moments']=()=>messageMoments();actions['message-contacts']=messageContacts;

new MutationObserver(syncMessageTabs).observe(screen,{childList:true,subtree:true});if(view==='messages')chatList();else syncMessageTabs();

function composeMoment(){if(zeroLock())return;closeSheet();view='moment-compose';active=null;rememberRoute();screen.innerHTML=`<section class="app-page moment-compose"><header class="page-head"><button class="icon-button" data-action="message-moments" aria-label="返回朋友圈">${icon('back')}</button><h1>发朋友圈</h1><button class="pill-button moment-send" data-action="moment-send">发送</button></header><label class="moment-draft-label" for="moment-draft">这一刻，想说点什么</label><textarea id="moment-draft" placeholder="分享此刻的心情…" aria-label="朋友圈文字">${esc(state.momentDraft||'')}</textarea><button class="moment-add-photo" data-action="moment-photo">${icon('plus')}<span>添加照片</span></button></section>`;document.querySelector('#moment-draft').oninput=e=>{state.momentDraft=e.target.value;persist()};syncMessageTabs()}
Object.assign(actions,{'moment-compose':composeMoment,'moment-photo':()=>toast('服务器错误'),'moment-send':()=>toast('朋友圈无法发出')});
