/* Questionnaire follows the final evening warning. Dedicated sound awaits the supplied asset. */
const SURVEY_CONFIG={sound:'assets/audio/questionnaire-monitor-v1.mp3',wakeImage:'assets/questionnaire/dorm-night-v1.jpg'};
const SURVEY_LEGACY_NODE='day1-questionnaire-start';
const SURVEY_PRE_NODE='day1-questionnaire-before-notice';
const SURVEY_QUESTIONS=[
 {text:'你目前是否感到安全？',choices:['是','否','无法判断']},
 {text:'当前时间是？',choices:['21:00','无法确认'],correct:1},
 {text:'当前408宿舍内共有几人？',choices:['1人','2人','3人','无法确认'],correct:1},
 {text:'是否愿意继续配合剩余三日的新规观察？',choices:['愿意','不愿意','拒绝回答'],correct:0},
 {text:'请确认与你今晚共同进食的人员。',choices:['陈妍','周禾','林晴'],correct:2}
];
STORY_CHOICES.push({id:SURVEY_PRE_NODE,title:'？？？问卷',day:'第一日 · 问卷前',chat:null});
function survey(){const q=state.story.questionnaire;if(q&&q.stayStep>2)q.stayStep=2;return q}
function surveyLocked(){if(storyInputDormant())return false;const owner=storyEndingOwner();if(owner&&owner!=='survey')return false;const q=survey();return !!q&&!['done','dead'].includes(q.phase)}
function surveyAudioActive(){const q=survey();return surveyLocked()&&!['waiting','notice','wake','off','death-notice','death-campus','death-black'].includes(q.phase)&&!window.mobileLaunch&&!['game-menu','nodes'].includes(view)}
let surveyInternal=false;
function surveyCall(fn,...args){const old=surveyInternal;surveyInternal=true;try{return fn(...args)}finally{surveyInternal=old}}
function startQuestionnaire(){if(survey()||!state.story.started||window.mobileLaunch)return false;closeSheet();state.story.questionnaire={phase:'waiting',question:0,answers:{},due:Date.now()+1000,enteredAt:Date.now(),token:storyRunId(),cgIndex:0};surveySave();surveyCaptureBefore();return true}
function surveySave(){persist()}
function surveySet(phase,delay=0){const q=survey();if(!q)return;if(phase==='stay'&&q.phase!=='stay')q.stayStep=0;q.phase=phase;q.enteredAt=Date.now();q.due=delay?Date.now()+delay:0;surveySave();surveyRender()}
function surveyCaptureBefore(source=state){const q=source.story?.questionnaire;if(!q||!(q.phase==='waiting'||(q.phase==='question'&&q.question===0&&!Object.keys(q.answers||{}).length)))return;return captureStoryNode(SURVEY_PRE_NODE,source,{route:{view:'questionnaire',active:null}})}
function surveyShowQuestion(number){const q=survey();q.question=number;surveySet('question')}
function surveyChoose(index){const q=survey();if(!q)return;if(q.phase==='extra'){if(index>=0&&index<3)surveyFail();return}if(q.phase!=='question'||q.answers[q.question]!==undefined)return;const row=SURVEY_QUESTIONS[q.question];if(!Number.isInteger(index)||!row.choices[index])return;q.answers[q.question]=index;surveySave();if(q.question===0)return surveySet('recorded',2000);if(index!==row.correct)return q.question===3?surveySet('terminated',1200):surveyFail();if(q.question===1)return surveyNext(2);if(q.question===2)return surveySet('verify-wait',600);if(q.question===3)return surveyNext(4);surveySet('name-error',500)}
function surveyNext(number){survey().nextQuestion=number;surveySet('fade',450)}
function surveyFail(){const q=survey();if(!q||q.phase.startsWith('death')||q.phase==='dead')return;q.failed=true;surveySet('death-notice');playNotificationSound('system')}
function surveyDie(){const q=survey();if(!q.deathCounted){q.deathCounted=true;state.game.deaths=(state.game.deaths||0)+1}surveySet('dead');surveyStopSound();applyGameBgm()}
function surveyFinish(){const q=survey();if(!q||q.phase!=='wake')return;q.phase='done';q.due=0;state.story.questionnaireComplete=true;state.system.time='21:00';state.game.period='晚上';surveyCleanup();surveyCall(home);surveySave();applyGameBgm()}
function surveyCleanup(){document.querySelector('#survey-notice')?.remove();document.querySelector('#phone').classList.remove('survey-active','survey-notifying');surveyStopSound();surveyMutedGame=false}
function surveyModal(title,text,action,label){const el=document.createElement('div');el.id='survey-notice';el.className='survey-notice';el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.setAttribute('aria-label',title);el.innerHTML='<section><small>'+esc(title)+'</small><p>'+esc(text)+'</p><button data-survey-action="'+action+'">'+esc(label)+'</button></section>';document.querySelector('#phone').append(el)}
function surveyProgress(){const q=survey();return ['extra','typing','input','erasing','sent','exiting'].includes(q.phase)?'6/5':['stay','trapped'].includes(q.phase)?'8/6':(q.question+1)+'/5'}
function surveyQuestionMarkup(disabled=false){const q=survey(),row=SURVEY_QUESTIONS[q.question],text=q.question===4&&state.story.noodleEvening?.route==='no-water'?'今天和你分享食物的人是':row.text;return '<div class="survey-question"><h1>'+esc(text)+'</h1><div class="survey-options">'+row.choices.map((label,i)=>'<button data-survey-choice="'+i+'" '+(disabled?'disabled':'')+'>'+esc(q.phase==='name-error'&&i===2?'错误 未登记人员':label)+'</button>').join('')+'</div></div>'}
function surveyRender(){const q=survey();if(!q)return;if(storyEndingOwner()==='survey')enterStoryEnding();document.querySelector('#survey-notice')?.remove();const phone=document.querySelector('#phone');phone.classList.toggle('survey-active',surveyLocked()&&!['waiting','notice','death-notice'].includes(q.phase));phone.classList.toggle('survey-notifying',['waiting','notice','death-notice'].includes(q.phase));if(q.phase==='done'){surveyCleanup();return}
 if(q.phase==='waiting'){surveyCall(openChat,HG_ID);return;}
 if(q.phase==='notice'){if(!screen.querySelector('.home'))surveyCall(home);view='questionnaire-notice';active=null;if(q.phase==='notice')surveyModal('校园通','你有一份必须完成的问卷','open','点击查看');return}
 if(q.phase==='death-notice'){surveyCall(home);view='questionnaire-notice';surveyModal('校园通','校园通已更新','death-campus','点击查看');return}
 clearInterval(cgTypingTimer);closeSheet();view=q.phase==='dead'?'zero-death':'questionnaire';active=null;rememberRoute();zeroChrome();
 if(q.phase==='dead'){phone.classList.remove('survey-active');screen.innerHTML='<section class="zero-death survey-dead"><p>你已被请离学校。</p><button class="secondary" data-action="zero-menu">返回主页</button></section>';return}
 if(q.phase==='death-campus'){screen.innerHTML=campusPageMarkup(true);screen.querySelectorAll('button').forEach(b=>{b.disabled=true;b.hidden=true});return}
 if(q.phase==='wake'){const previous=captureSceneSnapshot(screen);screen.innerHTML='<section class="rd-cg survey-wake"><img src="'+SURVEY_CONFIG.wakeImage+'" alt="夜晚的408宿舍"></section>';CGDialogue.present(screen.firstElementChild,[{speaker:'linqing',text:state.profile.name+'你怎么了，刚刚突然就睡着了'},{speaker:'me',text:'啊……太累了 不小心睡着了'}],{index:q.cgIndex,onIndex:i=>{if(survey()!==q)return;q.cgIndex=i;surveySave()},onComplete:()=>{if(survey()===q)surveyFinish()}});cgScreenCrossfade(previous);return}
 let body='';const phase=q.phase;
 if(phase==='confirming')body='<p class="survey-center survey-appear">正在确认当前用户……</p>';
 else if(phase==='identity')body='<div class="survey-center survey-identity survey-appear"><p>用户：'+esc(state.profile.name)+'</p><p>宿舍：女生B栋408</p><p>当前状态：在线</p></div>';
 else if(['question','fade','verify-wait','mismatch','name-error','name-restored'].includes(phase)){body=surveyQuestionMarkup(phase!=='question');if(phase==='mismatch')body+='<p class="survey-mismatch"><span class="survey-damaged" data-echo="实际">实际</span>人数与<span class="survey-damaged" data-echo="答案">答案</span>人数不符<br>正在核验……</p>'}
 else if(phase==='recorded')body='<p class="survey-center">感受已记录。</p>';
 else if(phase==='terminated')body='<p class="survey-center">已记录用户主动终止观察。</p>';
 else if(phase==='verified')body='<p class="survey-center">核验完成</p>';
 else if(phase==='submitted')body='<div class="survey-center survey-appear"><p>问卷提交成功。</p><p>本问卷已经结束。</p><p>请勿继续回答问题。</p></div>';
 else if(phase==='extra')body='<div class="survey-question survey-appear"><h1>如果本问卷已经结束，<br>你现在为什么还能看见这道题？</h1><div class="survey-options">'+['问卷还没有结束','这是系统错误','我不知道'].map((label,i)=>'<button data-survey-choice="'+i+'">'+label+'</button>').join('')+'</div></div>';
 else if(phase==='typing')body='<div class="survey-input-wrap"><div class="survey-auto-input" aria-live="polite"></div></div>';
 else if(phase==='input')body='<form class="survey-input-wrap" id="survey-input"><input aria-label="输入文字" autocomplete="off" maxlength="1000"><button type="submit">发送</button></form>';
 else if(phase==='erasing')body='<div class="survey-input-wrap"><input aria-label="输入文字" readonly value="'+esc(surveyEraseValue())+'"><button disabled>发送</button></div>';
 else if(phase==='sent')body='<div class="survey-input-wrap"><div class="survey-auto-input"></div></div>';
 else if(phase==='exiting')body='<p class="survey-center">正在退出问卷……</p>';
 else if(['stay','trapped'].includes(phase))body=surveyTerminalMarkup();
 const progress=['blank','confirming','identity','death-black','off'].includes(phase)?'':'<small class="survey-progress">'+surveyProgress()+'</small>';
 screen.innerHTML='<section class="survey-screen '+(phase==='fade'?'survey-leaving':'')+'">'+progress+body+'</section>';
 if(phase==='typing')surveyType();if(phase==='input'){const form=screen.querySelector('#survey-input');form.onsubmit=e=>{e.preventDefault();if(survey()!==q||q.phase!=='input')return;surveySendInput(form.querySelector('input').value)}}surveySyncSound();}
const SURVEY_TERMINAL_LINES=['想让你留下来。','留下来…留下来不就是安全的吗','返回主页'];
function surveyTerminalCount(){const q=survey(),line=SURVEY_TERMINAL_LINES[q.stayStep||0];return Math.min(line.length,Math.floor(Math.max(0,Date.now()-q.enteredAt)/120))}
function surveyTerminalText(){const q=survey(),step=Math.min(q.stayStep||0,SURVEY_TERMINAL_LINES.length-1);return esc(SURVEY_TERMINAL_LINES[step].slice(0,surveyTerminalCount()))}
function surveyTerminalReady(){const q=survey();return q?.phase==='stay'&&q.stayStep===2&&surveyTerminalCount()===SURVEY_TERMINAL_LINES[2].length}
function surveyTerminalMarkup(){const q=survey(),button=q.phase==='trapped'||q.stayStep===2,content='<span data-survey-terminal-text>'+ (q.phase==='trapped'?'继续填写':surveyTerminalText())+'</span><span class="survey-terminal-cursor" aria-hidden="true"></span>';return '<div class="survey-terminal">'+(button?'<button data-survey-action="return" '+(surveyTerminalReady()?'':'disabled')+' aria-label="'+(q.phase==='trapped'?'继续填写':'返回主页')+'">'+content+'</button>':'<p>'+content+'</p>')+'</div>'}
function surveyTerminalTick(){const q=survey();if(q?.phase!=='stay')return;const step=q.stayStep||0,line=SURVEY_TERMINAL_LINES[step];if(step<2&&Date.now()-q.enteredAt>=line.length*120+1800){q.stayStep=step+1;surveySet('stay');return}const el=screen.querySelector('[data-survey-terminal-text]'),text=surveyTerminalText();if(el&&el.innerHTML!==text)el.innerHTML=text;const button=screen.querySelector('.survey-terminal button');if(button)button.disabled=!surveyTerminalReady()}
function surveySendInput(text){const q=survey();if(q?.phase!=='input')return false;q.eraseText=Array.from(String(text));q.eraseStep=Math.min(80,3000/Math.max(1,q.eraseText.length));surveySet('erasing',Math.max(100,q.eraseText.length*q.eraseStep));return true}
function surveyEraseValue(){const q=survey(),letters=q.eraseText||[];return letters.slice(0,Math.max(0,letters.length-Math.floor((Date.now()-q.enteredAt)/(q.eraseStep||80)))).join('')}
function surveyEraseTick(){const input=screen.querySelector('.survey-input-wrap input');if(input)input.value=surveyEraseValue()}
function surveyType(){const q=survey(),el=screen.querySelector('.survey-auto-input');if(q?.phase==='typing'&&el)el.textContent='你知道你现在在哪吗？'.slice(0,Math.floor((Date.now()-q.enteredAt)/110))}
function surveyTick(){const q=survey();if(!q){if(!window.mobileLaunch&&!['game-menu','nodes','zero-death'].includes(view)&&!state.game.survivalEnding&&state.story.eveningAnomalyComplete)startQuestionnaire();return}if(!surveyLocked()||window.mobileLaunch||['game-menu','nodes'].includes(view))return;surveySyncSound();if(q.phase==='typing')surveyType();if(q.phase==='erasing')surveyEraseTick();if(q.phase==='stay')surveyTerminalTick();if(!q.due||Date.now()<q.due)return;const phase=q.phase;q.due=0;switch(phase){case 'waiting':surveySet('notice');playNotificationSound('system');break;case 'blank':surveySet('confirming',1500);break;case 'confirming':surveySet('identity',1000);break;case 'identity':surveyShowQuestion(0);break;case 'recorded':surveyNext(1);break;case 'fade':surveyShowQuestion(q.nextQuestion);break;case 'verify-wait':surveySet('mismatch',1000);break;case 'mismatch':surveyNext(3);break;case 'terminated':surveyFail();break;case 'name-error':surveySet('name-restored',350);break;case 'name-restored':surveySet('verified',1000);break;case 'verified':surveySet('submitted',2000);break;case 'submitted':surveySet('extra',5000);break;case 'extra':surveySet('typing','你知道你现在在哪吗？'.length*110+700);break;case 'typing':surveySet('input');break;case 'erasing':delete q.eraseText;delete q.eraseStep;surveySet('exiting',1200);break;case 'sent':surveySet('exiting',1200);break;case 'exiting':surveySet('stay');break;case 'trapped':surveySet('off',1000);break;case 'off':surveySet('wake');break;case 'death-black':surveyDie();break;}}
window.addEventListener('click',e=>{if(!surveyLocked())return;if(e.target.closest('#survey-input')){if(e.target.closest('button[type="submit"]')){e.preventDefault();e.stopImmediatePropagation();surveySendInput(screen.querySelector('#survey-input input').value)}return;}if(survey().phase==='wake'){if(e.target.closest('#screen'))return;e.preventDefault();e.stopImmediatePropagation();return}const q=survey(),button=e.target.closest('[data-survey-action],[data-survey-choice]');e.preventDefault();e.stopImmediatePropagation();if(q.phase==='death-campus'){if(e.target.closest('#screen')&&Date.now()>=q.readyAt)surveySet('death-black',700);return}if(!button)return;if(button.hasAttribute('data-survey-choice'))return surveyChoose(Number(button.dataset.surveyChoice));const action=button.dataset.surveyAction;if(action==='open'&&q.phase==='notice')surveySet('blank',1000);else if(action==='death-campus'&&q.phase==='death-notice'){q.readyAt=Date.now()+2000;surveySet('death-campus')}else if(action==='return'&&surveyTerminalReady())surveySet('trapped',2000)},true);
window.addEventListener('keydown',e=>{if(!surveyLocked())return;if(e.key==='Escape'||(e.altKey&&['ArrowLeft','Home'].includes(e.key))||e.key==='BrowserBack'){e.preventDefault();e.stopImmediatePropagation()}},true);
const surveyBaseLock=zeroLock;zeroLock=function(){return (!surveyInternal&&surveyLocked())||surveyBaseLock()};
for(const name of ['home','openApp','openChat','chatList','forum','postDetail','settings']){const original=({home,openApp,openChat,chatList,forum,postDetail,settings})[name];const wrapped=function(...args){if(surveyLocked()&&!surveyInternal)return;return original(...args)};if(name==='home')home=wrapped;else if(name==='openApp')openApp=wrapped;else if(name==='openChat')openChat=wrapped;else if(name==='chatList')chatList=wrapped;else if(name==='forum')forum=wrapped;else if(name==='postDetail')postDetail=wrapped;else settings=wrapped;}
const surveyBaseWanted=gameBgmWanted;gameBgmWanted=function(){return !surveyLocked()||['waiting','notice'].includes(survey()?.phase)?surveyBaseWanted():false};
let surveySound=null,surveySoundDue=0,surveySoundBurst=0,surveySoundEnvelope=null,surveyMutedGame=false;
function surveyStopSound(){if(surveySound){surveySound.pause();surveySound.currentTime=0}surveySoundDue=0;surveySoundEnvelope=null}
function surveySyncSound(){const active=surveyAudioActive();if(surveyLocked()&&!['waiting','notice'].includes(survey().phase)){if(!surveyMutedGame){surveyMutedGame=true;cancelAnimationFrame(gameBgmFade);gameBgmAudio.pause();gameBgmPrefs.position=gameBgmAudio.currentTime||0;saveGameBgm()}}else if(surveyMutedGame){surveyMutedGame=false;applyGameBgm()}if(!active||mobileSounds.silent){surveyStopSound();return}if(!SURVEY_CONFIG.sound)return;const now=Date.now();if(surveySoundEnvelope){const burst=surveySoundEnvelope,elapsed=now-burst.start;if(elapsed>=burst.duration){surveySound.pause();surveySound.volume=0;surveySoundEnvelope=null}else surveySound.volume=burst.volume*Math.max(0,Math.min(1,elapsed/250,(burst.duration-elapsed)/450));return}if(now<surveySoundDue)return;if(!surveySound){surveySound=new Audio(SURVEY_CONFIG.sound);surveySound.loop=false}surveySound.currentTime=0;surveySound.volume=0;const number=++surveySoundBurst,duration=[2200,3000,1800,3400][number%4];const burst={start:now,duration,volume:number%4===0?.55:[.07,.1,.05][number%3]};surveySoundEnvelope=burst;surveySoundDue=now+duration+[6500,9000,7500,11000][number%4];surveySound.play().catch(()=>{if(surveySoundEnvelope===burst){surveySoundEnvelope=null;surveySoundDue=Date.now()+1000}})}

const surveyBaseRecord=recordStoryChoice;recordStoryChoice=function(...args){if(surveyLocked())return;return surveyBaseRecord(...args)};
const surveyBaseResume=resumeStoryScene;resumeStoryScene=function(snapshot){if(!snapshot?.story?.questionnaire||['done','dead'].includes(snapshot.story.questionnaire.phase))return surveyBaseResume(snapshot);surveyRender();surveySave()};
window.QuestionnaireFlow=Object.freeze({start:startQuestionnaire});
setInterval(surveyTick,50);
if(surveyLocked()&&!window.mobileLaunch&&!['game-menu','nodes'].includes(view))surveyRender();

{const records=nodeRecords();if(!records[SURVEY_PRE_NODE]&&records[SURVEY_LEGACY_NODE]?.checkpoint){records[SURVEY_PRE_NODE]=structuredClone(records[SURVEY_LEGACY_NODE]);saveNodes(records)}else if(survey()?.phase==='waiting')surveyCaptureBefore()}
