/* Shen Kexin's personal profile and read-only moments. */
const SHEN_PROFILE={name:'沈可欣',signature:'天气是时光机。',moments:[
 {id:'shen-birthday',date:'2045年1月7日 21:34',text:'今天又长大一岁了。自己买给自己的蛋糕，新的一岁希望自己不要再下意识讨好任何人了。',image:'assets/shen-cream-cake.jpg',imageAlt:'桌上的普通奶油蛋糕'}
]};
let shenOrigin={chat:'shen-friend',members:false};
function shenAvatarButton(){return `<button class="npc-avatar-button" data-action="zero-shen-profile" aria-label="查看沈可欣个人资料">${avatar('shen')}</button>`}
function shenProfile(returning=false){if(zeroLock())return;if(!returning)shenOrigin={chat:active||'shen-friend',members:!!document.querySelector('#overlay .sheet')};closeSheet();view='shen-profile';active=null;const p=SHEN_PROFILE;screen.innerHTML=`<section class="app-page lin-profile"><header class="page-head"><button class="icon-button" data-action="zero-shen-back" aria-label="返回聊天">${icon('back')}</button><h1>个人资料</h1></header><div class="lin-profile-card">${avatar('shen')}<h2>${esc(p.name)}</h2><p>个性签名：${esc(p.signature)}</p></div><div class="settings-group">${settingItem('photo','朋友圈','zero-shen-moments')}</div></section>`;screen.scrollTop=0}
function shenMoments(){if(zeroLock())return;closeSheet();view='shen-moments';active=null;const p=SHEN_PROFILE;screen.innerHTML=`<section class="app-page lin-moments"><header class="page-head"><button class="icon-button" data-action="zero-shen-return" aria-label="返回沈可欣个人资料">${icon('back')}</button><h1>沈可欣的朋友圈</h1></header><div class="lin-feed-owner">${avatar('shen')}<div><strong>${esc(p.name)}</strong><p>${esc(p.signature)}</p></div></div>${p.moments.filter(m=>!m.condition||state.game.flags?.[m.condition]).map(m=>`<article class="lin-moment"><time>${esc(m.date)}</time><p class="lin-moment-text">${esc(m.text)}</p>${m.image?`<div class="lin-moment-photo"><img src="${esc(m.image)}" alt="${esc(m.imageAlt)}"></div>`:''}</article>`).join('')}</section>`;screen.scrollTop=0}
Object.assign(actions,{'zero-shen-profile':()=>shenProfile(),'zero-shen-return':()=>shenProfile(true),'zero-shen-moments':shenMoments,'zero-shen-back':()=>{openChat(shenOrigin.chat);if(shenOrigin.members)actions['chat-options']()}});
const shenChatBase=openChat;openChat=function(id){shenChatBase(id);if(view==='chat'&&active===id&&id==='shen-friend'){const a=screen.querySelector('.chat-head>.avatar');if(a)a.outerHTML=shenAvatarButton()}};
const shenMessageBase=renderMessage;renderMessage=function(m,c){const html=shenMessageBase(m,c);return (m.hgWho==='shen'||m.sender==='shen')?html.replace(avatar('shen'),shenAvatarButton()):html};
const shenMembersBase=actions['chat-options'];actions['chat-options']=()=>{shenMembersBase();const source=C.avatars.find(a=>a.id==='shen')?.src;if(!source)return;document.querySelectorAll('#overlay .avatar img').forEach(img=>{if(img.getAttribute('src')!==source||img.closest('button'))return;img.closest('.avatar').outerHTML=shenAvatarButton()})};
